language: ruby
rvm:
  - 2.2.3
  - jruby
  - rbx-2
  
env:
  - DB=postgres

before_script:
  - "cp config/database.ci.yml config/database.yml"
  - "RAILS_ENV=test bundle exec rake db:create"
  
script: "RAILS_ENV=test bundle exec rake spec"

