# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a495d0bb4d94f268ebd64f1823a8fb2bdbf8ca0ad6d0167df25ff3adb352127a9a822d6cacf34766ab3acdd12a983b485dcedc2e7f68aac8f3775d406493e83
  email: flashcards174@project.com
  url: https://flashcards174.herokuapp.com/
test:
  secret_key_base: 1011b9a98fe88d82a0e93a1ae3e799f564689cfb3fb57a3105743a9bd6c1c76baedc46633ae8605bc90d7821d2a8d6a9e8fe7fca4bf4e807c1b78eb228a8c5aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
